name: SNEARS
favicon: null
layout_spectrum: 0.8947
typography_spectrum: 0.64998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01050e'
    - '#5f6367'
    - '#95a3b4'
    - '#8fd5d5'
    - '#f6f8f9'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
