name: SNEARS
favicon: null
layout_spectrum: 0.09780797199346125
typography_spectrum: 0.25023432774469256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6536542039830238
  lightness: 0.21151145338080823
  saturation: 0.5622553848661482
  rhythmicContrast: 0.25622110697440803
purpose: []
